#!/usr/bin/env python3
"""Generates test/SpectralMatrix.t.sol — the venue's conformance matrix.

Every cell is a distinct guard test: a state, an operation, an actor, and the exact
outcome the contract must produce (a named error selector, or a specific resulting
state). The matrix is exhaustive over states × operations × actors, so a missing or
weakened guard anywhere shows up as a failing cell rather than as a silent gap.

Reach a given state through the public API only — no storage pokes, so the setups
themselves are part of what is being tested.

Run:  python3 test/gen_matrix_tests.py   (then: forge test)
"""

import pathlib

HEADER = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Spectral} from "../src/Spectral.sol";

/// @title SpectralMatrix — conformance matrix over states x operations x actors
/// @notice GENERATED by test/gen_matrix_tests.py — edit the generator, not this file.
/// Each test asserts the exact error selector or the exact resulting state, so a
/// weakened guard in any state fails a named cell.
contract SpectralMatrixTest is Test {
    Spectral o;

    address buyer = address(0xB0B);
    address executor = address(0xE0E);
    address taker = address(0x7A4E);
    address stranger = address(0x57A);

    uint256 constant UNITS = 10;
    uint256 constant PPU = 1 ether;
    uint256 constant ESCROW = UNITS * PPU;
    uint256 constant DAY = 1 days;

    function setUp() public {
        o = new Spectral();
        vm.deal(buyer, 10_000 ether);
        vm.deal(executor, 10_000 ether);
        vm.deal(taker, 10_000 ether);
        vm.deal(stranger, 10_000 ether);
    }

    // ---------- state construction, through the public API only ----------

    function _open() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
    }

    function _stalled() internal returns (uint256 id) {
        id = _open();
        vm.prank(executor);
        o.declareStalled(id);
    }

    function _listed() internal returns (uint256 id) {
        id = _stalled();
        o.listObligation(id, block.timestamp + DAY);
    }

    function _taken() internal returns (uint256 id) {
        id = _listed();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertTakerIsRecorded(id, taker);
    }

    /// @dev two units counted, then the executor quits and a taker posts the bond
    function _takenPartial() internal returns (uint256 id) {
        id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 0, bytes32(uint256(1)));
        o.countUnit(id, 1, bytes32(uint256(2)));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
    }

    function _settled() internal returns (uint256 id) {
        id = _open();
        for (uint256 i; i < UNITS; i++) {
            vm.prank(executor);
            o.countUnit(id, i, bytes32(uint256(i) + 1));
        }
    }

    function _closed() internal returns (uint256 id) {
        id = _takenPartial();
        vm.warp(block.timestamp + DAY + 1);
        o.closeFailed(id);
    }

    function _assertState(uint256 id, Spectral.State want) internal view {
        assertEq(uint256(o.stateOf(id)), uint256(want), "state mismatch");
    }

    /// @dev a setup that took the obligation must have recorded THIS contract's taker,
    /// not the test contract: a view call inside a pranked call's arguments eats the prank.
    function _assertTakerIsRecorded(uint256 id, address who) internal view {
        (, , , , , , , , , address recorded, , ) = o.jobs(id);
        assertEq(recorded, who, "the recorded taker is not the intended taker");
    }

'''

FOOTER = "}\n"


def cell(name, setup, body, doc):
    call = setup if setup.startswith("_") else "_" + setup
    return (
        f"    /// @dev {doc}\n"
        f"    function test_{name}() public {{\n"
        f"        uint256 id = {call}();\n"
        f"{body}"
        f"    }}\n"
    )


def expect_revert(err, extra=""):
    return f"        vm.expectRevert({err}{extra});\n"


def main():
    out = [HEADER]
    count = 0

    def add(res):
        nonlocal count
        out.append(res)
        count += 1

    # ============ A. state x operation x actor ============
    # Each entry: (state, op-name, setup, call, expectation)
    # expectation: ("ok", resulting_state) | ("err", selector) | ("claim", actor)
    MATRIX = {
        "Open": [
            ("countByExecutor", "open", "executor", "countUnit(id, 9, bytes32(uint256(0xABC)))", "ok", "Open"),
            ("countByTaker", "open", "taker", "countUnit(id, 9, bytes32(uint256(0xABC)))", "err", "NotExecutor"),
            ("countByStranger", "open", "stranger", "countUnit(id, 9, bytes32(uint256(0xABC)))", "err", "NotExecutor"),
            ("stallByExecutor", "open", "executor", "declareStalled(id)", "ok", "Stalled"),
            ("stallByStrangerEarly", "open", "stranger", "declareStalled(id)", "err", "DeadlineNotReached"),
            ("stallByStrangerLate", "openLate", "stranger", "declareStalled(id)", "ok", "Stalled"),
            ("listFromOpen", "open", "stranger", "listObligation(id, block.timestamp + DAY)", "err", "AlreadyStalled"),
            ("takeFromOpen", "open", "taker", "takeObligation{value: o.requiredBond(id)}(id)", "err", "NothingToTake"),
            ("takeUnderBondFromOpen", "open", "taker", "takeObligation{value: 1}(id)", "err", "NothingToTake"),
            ("closeEarlyFromOpen", "open", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("closeLateFromOpen", "openLate", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("claimByExecutorFromOpen", "open", "executor", "claim()", "err", "NothingToClaim"),
            ("claimByBuyerFromOpen", "open", "buyer", "claim()", "err", "NothingToClaim"),
            ("claimByTakerFromOpen", "open", "taker", "claim()", "err", "NothingToClaim"),
        ],
        "Stalled": [
            ("countByExecutor", "stalled", "executor", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByTaker", "stalled", "taker", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByStranger", "stalled", "stranger", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("stallByExecutor", "stalled", "executor", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerEarly", "stalled", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerLate", "stalledLate", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("listFromStalled", "stalled", "stranger", "listObligation(id, block.timestamp + DAY)", "ok", "Listed"),
            ("takeFromStalled", "stalled", "taker", "takeObligation{value: o.requiredBond(id)}(id)", "err", "NothingToTake"),
            ("takeUnderBondFromStalled", "stalled", "taker", "takeObligation{value: 1}(id)", "err", "NothingToTake"),
            ("closeEarlyFromStalled", "stalled", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("closeLateFromStalled", "stalledLate", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("claimByExecutorFromStalled", "stalled", "executor", "claim()", "err", "NothingToClaim"),
            ("claimByBuyerFromStalled", "stalled", "buyer", "claim()", "err", "NothingToClaim"),
            ("claimByTakerFromStalled", "stalled", "taker", "claim()", "err", "NothingToClaim"),
        ],
        "Listed": [
            ("countByExecutor", "listed", "executor", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByTaker", "listed", "taker", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByStranger", "listed", "stranger", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("stallByExecutor", "listed", "executor", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerEarly", "listed", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerLate", "listedLate", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("listFromListed", "listed", "stranger", "listObligation(id, block.timestamp + DAY)", "err", "AlreadyStalled"),
            ("takeFromListed", "listed", "taker", "takeObligation{value: o.requiredBond(id)}(id)", "ok", "Taken"),
            ("takeUnderBondFromListed", "listed", "taker", "takeObligation{value: o.requiredBond(id) - 1}(id)", "err", "BondTooSmall"),
            ("closeEarlyFromListed", "listed", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("closeLateFromListed", "listedLate", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("claimByExecutorFromListed", "listed", "executor", "claim()", "err", "NothingToClaim"),
            ("claimByBuyerFromListed", "listed", "buyer", "claim()", "err", "NothingToClaim"),
            ("claimByTakerFromListed", "listed", "taker", "claim()", "err", "NothingToClaim"),
        ],
        "Taken": [
            ("countByTaker", "taken", "taker", "countUnit(id, 9, bytes32(uint256(1)))", "ok", "Taken"),
            ("countByExecutor", "taken", "executor", "countUnit(id, 9, bytes32(uint256(1)))", "err", "NotExecutor"),
            ("countByStranger", "taken", "stranger", "countUnit(id, 9, bytes32(uint256(1)))", "err", "NotExecutor"),
            ("stallByExecutor", "taken", "executor", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerEarly", "taken", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerLate", "takenLate", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("listFromTaken", "taken", "stranger", "listObligation(id, block.timestamp + DAY)", "err", "AlreadyStalled"),
            ("takeFromTaken", "taken", "stranger", "takeObligation{value: o.requiredBond(id)}(id)", "err", "NothingToTake"),
            ("takeUnderBondFromTaken", "taken", "stranger", "takeObligation{value: 1}(id)", "err", "NothingToTake"),
            ("closeEarlyFromTaken", "taken", "stranger", "closeFailed(id)", "err", "DeadlineNotReached"),
            ("closeLateFromTaken", "takenPartialLate", "stranger", "closeFailed(id)", "ok", "Closed"),
            ("claimByExecutorFromTaken", "taken", "executor", "claim()", "err", "NothingToClaim"),
            ("claimByBuyerFromTaken", "taken", "buyer", "claim()", "err", "NothingToClaim"),
            ("claimByTakerFromTaken", "taken", "taker", "claim()", "err", "NothingToClaim"),
        ],
        "Settled": [
            ("countByExecutorFromSettled", "settled", "executor", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByTakerFromSettled", "settled", "taker", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByStrangerFromSettled", "settled", "stranger", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("stallByExecutorFromSettled", "settled", "executor", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerEarlyFromSettled", "settled", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerLateFromSettled", "settledLate", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("listFromSettled", "settled", "stranger", "listObligation(id, block.timestamp + DAY)", "err", "AlreadyStalled"),
            ("takeFromSettled", "settled", "stranger", "takeObligation{value: o.requiredBond(id)}(id)", "err", "NothingToTake"),
            ("takeUnderBondFromSettled", "settled", "stranger", "takeObligation{value: 1}(id)", "err", "NothingToTake"),
            ("closeEarlyFromSettled", "settled", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("closeLateFromSettled", "settledLate", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("claimByExecutorFromSettled", "settled", "executor", "claim()", "claim", ""),
            ("claimByBuyerFromSettled", "settled", "buyer", "claim()", "err", "NothingToClaim"),
            ("claimByTakerFromSettled", "settled", "taker", "claim()", "err", "NothingToClaim"),
        ],
        "Closed": [
            ("countByExecutorFromClosed", "closed", "executor", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByTakerFromClosed", "closed", "taker", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("countByStrangerFromClosed", "closed", "stranger", "countUnit(id, 9, bytes32(uint256(1)))", "err", "JobNotOpen"),
            ("stallByExecutorFromClosed", "closed", "executor", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerEarlyFromClosed", "closed", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("stallByStrangerLateFromClosed", "closedLate", "stranger", "declareStalled(id)", "err", "AlreadyStalled"),
            ("listFromClosed", "closed", "stranger", "listObligation(id, block.timestamp + DAY)", "err", "AlreadyStalled"),
            ("takeFromClosed", "closed", "stranger", "takeObligation{value: o.requiredBond(id)}(id)", "err", "NothingToTake"),
            ("takeUnderBondFromClosed", "closed", "stranger", "takeObligation{value: 1}(id)", "err", "NothingToTake"),
            ("closeEarlyFromClosed", "closed", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("closeLateFromClosed", "closedLate", "stranger", "closeFailed(id)", "err", "NothingToTake"),
            ("claimByExecutorFromClosed", "closed", "executor", "claim()", "claim", ""),
            ("claimByBuyerFromClosed", "closed", "buyer", "claim()", "claim", ""),
            ("claimByTakerFromClosed", "closed", "taker", "claim()", "err", "NothingToClaim"),
        ],
    }

    # late setups warp past every deadline in the job
    LATE = {
        "openLate": "        vm.warp(block.timestamp + DAY + 1);\n",
        "stalledLate": "        vm.warp(block.timestamp + DAY + 1);\n",
        "listedLate": "        vm.warp(block.timestamp + DAY + 1);\n",
        "takenLate": "        vm.warp(block.timestamp + DAY + 1);\n",
        "takenPartialLate": "        vm.warp(block.timestamp + DAY + 1);\n",
        "settledLate": "        vm.warp(block.timestamp + DAY + 1);\n",
        "closedLate": "        vm.warp(block.timestamp + DAY + 1);\n",
    }

    out.append("    // ================= A. states x operations x actors =================\n\n")
    for state, rows in MATRIX.items():
        out.append(f"    // ---------- from {state} ----------\n\n")
        for name, setup, actor, call, kind, extra in rows:
            warp = LATE.get(setup, "")
            body = warp
            call_ = call
            if "requiredBond" in call_:
                body += "        uint256 required = o.requiredBond(id);\n"
                call_ = call_.replace("o.requiredBond(id)", "required")
            body += f"        vm.prank({actor});\n"
            if kind == "ok":
                body += f"        o.{call_};\n"
                body += f'        _assertState(id, Spectral.State.{extra});\n'
            elif kind == "err":
                if extra == "BondTooSmall":
                    body += "        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));\n"
                    body += f"        o.{call_};\n"
                else:
                    body += f"        vm.expectRevert(Spectral.{extra}.selector);\n"
                    body += f"        o.{call_};\n"
            else:  # claim pays
                body = body.replace(f"        vm.prank({actor});\n", "")
                body += "        uint256 owed = o.credits(" + actor + ");\n"
                body += "        uint256 before = " + actor + ".balance;\n"
                body += "        vm.prank(" + actor + ");\n"
                body += "        o.claim();\n"
                body += f"        assertEq({actor}.balance - before, owed);\n"
                body += f"        assertEq(o.credits({actor}), 0);\n"
            doc_setup = {"openLate": "open, past the work deadline", "stalledLate": "stalled, past the deadline",
                         "listedLate": "listed, past the deadline", "takenLate": "taken, past the deadline",
                         "takenPartialLate": "taken with units outstanding, past the taker deadline",
                         "settledLate": "settled, past the deadline", "closedLate": "closed, past the deadline"}
            add(cell(f"matrix_{state.lower()}_{name}", setup,
                     body, f"from {doc_setup.get(setup, setup)}: {name}"))

    # ============ B. unit index boundary ============
    out.append("\n    // ================= B. unit index boundary =================\n\n")
    for i in range(UNITS := 10):
        add(cell(f"index_{i}_countable", "open", (
            f"        vm.prank(executor);\n"
            f"        o.countUnit(id, {i}, bytes32(uint256({i}) + 1));\n"
            f"        assertEq(o.remainingUnits(id), UNITS - 1);\n"),
            f"index {i} is inside the unit range"))
    for i in (10, 11, 255):
        add(cell(f"index_{i}_refused", "open", (
            f"        vm.prank(executor);\n"
            f"        vm.expectRevert(Spectral.UnitOutOfRange.selector);\n"
            f"        o.countUnit(id, {i}, bytes32(uint256(1)));\n"),
            f"index {i} is outside the unit range"))
    add(cell("index_uint256_max_refused", "open", (
        "        vm.prank(executor);\n"
        "        vm.expectRevert(Spectral.UnitOutOfRange.selector);\n"
        "        o.countUnit(id, type(uint256).max, bytes32(uint256(1)));\n"),
        "index type(uint256).max is outside the unit range"))
    for i in range(UNITS):
        add(cell(f"index_{i}_duplicate_refused", "open", (
            f"        vm.startPrank(executor);\n"
            f"        o.countUnit(id, {i}, bytes32(uint256(1)));\n"
            f"        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);\n"
            f"        o.countUnit(id, {i}, bytes32(uint256(2)));\n"
            f"        vm.stopPrank();\n"),
            f"unit {i} cannot be counted twice"))

    # ============ B2. a wider unit range (off-by-one at larger N) ============
    out.append("\n    // ================= B2. wider unit range =================\n\n")
    for i in range(20):
        add(cell(f"wide_index_{i}_countable", "open20", (
            f"        vm.prank(executor);\n"
            f"        o.countUnit(id, {i}, bytes32(uint256({i}) + 1));\n"
            f"        assertEq(o.remainingUnits(id), 20 - 1);\n"),
            f"index {i} is countable in a twenty-unit job"))
    for i in (20, 21, 1024):
        add(cell(f"wide_index_{i}_refused", "open20", (
            f"        vm.prank(executor);\n"
            f"        vm.expectRevert(Spectral.UnitOutOfRange.selector);\n"
            f"        o.countUnit(id, {i}, bytes32(uint256(1)));\n"),
            f"index {i} is refused in a twenty-unit job"))

    # ============ C. bond boundary ============
    out.append("\n    // ================= C. bond boundary =================\n\n")
    for remaining in range(1, 8):
        add(cell(f"bond_exact_{remaining}_units_remain", f"partial{remaining}", (
            "        uint256 required = o.requiredBond(id);\n"
            "        vm.prank(taker);\n"
            "        o.takeObligation{value: required}(id);\n"
            "        _assertState(id, Spectral.State.Taken);\n"
            "        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);\n"
            "        assertEq(bond, required);\n"),
            f"exact bond accepted with {remaining} units remaining"))
        add(cell(f"bond_one_wei_short_{remaining}_units_remain", f"partial{remaining}", (
            "        uint256 required = o.requiredBond(id);\n"
            "        vm.prank(taker);\n"
            "        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));\n"
            "        o.takeObligation{value: required - 1}(id);\n"),
            f"one wei short of the bond is refused with {remaining} units remaining"))
        add(cell(f"bond_overpay_{remaining}_units_remain", f"partial{remaining}", (
            "        uint256 required = o.requiredBond(id);\n"
            "        vm.prank(taker);\n"
            "        o.takeObligation{value: required + 1}(id);\n"
            "        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);\n"
            "        assertEq(bond, required + 1);\n"),
            f"an overpaid bond is recorded in full with {remaining} units remaining"))
        add(cell(f"bond_formula_{remaining}_units_remain", f"partial{remaining}", (
            "        uint256 remaining_units = o.remainingUnits(id);\n"
            "        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);\n"),
            f"the bond is exactly half the remaining escrow with {remaining} units remaining"))

    # ============ E2. payout and remainder exactness ============
    out.append("\n    // ================= E2. payout and remainder exactness =================\n\n")
    for k in range(1, 9):
        add(cell(f"paid_exactly_for_{k}_units", "open", (
            f"        vm.startPrank(executor);\n"
            f"        for (uint256 i; i < {k}; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
            f"        vm.stopPrank();\n"
            f"        assertEq(o.credits(executor), 0);\n"
            f"        assertEq(o.remainingUnits(id), UNITS - {k});\n"),
            f"after {k} units: nothing is owed yet and the remainder is exact"))
        add(cell(f"settled_for_{k}_units_pays_{k}_times_price", f"partial{9 - k}", (
            "        uint256 bond = o.requiredBond(id);\n"
            "        vm.prank(taker);\n"
            "        o.takeObligation{value: bond}(id);\n"
            "        _assertTakerIsRecorded(id, taker);\n"
            "        vm.startPrank(taker);\n"
            "        for (uint256 i = UNITS - " + str(9 - k) + "; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
            "        vm.stopPrank();\n"
            "        _assertState(id, Spectral.State.Settled);\n"
            f"        assertEq(o.credits(executor), {1 + k} * PPU);\n"
            f"        assertEq(o.credits(taker), {9 - k} * PPU + bond);\n"
            "        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));\n"),
            f"a split of {1 + k} and {9 - k} units pays each side for exactly what it counted"))

    # ============ D. deadline boundary ============
    out.append("\n    // ================= D. deadline boundary =================\n\n")
    for label, offset in (("before", "-1"), ("exactly_at", "0"), ("after", "+1")):
        expr = {"before": "id_workDeadline - 1", "exactly_at": "id_workDeadline", "after": "id_workDeadline + 1"}[label]
        for actor in ("executor", "stranger"):
            allowed = actor == "executor" or label != "before"
            body = f"        uint256 workDeadline = workDeadlineOf(id);\n        vm.warp({expr});\n        vm.prank({actor});\n"
            if allowed:
                body += "        o.declareStalled(id);\n        _assertState(id, Spectral.State.Stalled);\n"
            else:
                body += "        vm.expectRevert(Spectral.DeadlineNotReached.selector);\n        o.declareStalled(id);\n"
            out.append(cell(f"workdeadline_{label}_by_{actor}",
                            "openWithDeadline",
                            body,
                            f"the work deadline {label}: {actor} {'may' if allowed else 'may not'} stall"))
            count += 1
    for label, expr in (("before", "takerDeadline - 1"), ("exactly_at", "takerDeadline"), ("after", "takerDeadline + 1")):
        body = f"        uint256 takerDeadline = takerDeadlineOf(id);\n        vm.warp({expr});\n"
        if label == "before":
            body += ("        vm.expectRevert(Spectral.DeadlineNotReached.selector);\n"
                     "        o.closeFailed(id);\n"
                     "        _assertState(id, Spectral.State.Taken);\n")
        else:
            body += ("        o.closeFailed(id);\n"
                     "        _assertState(id, Spectral.State.Closed);\n")
        add(cell(f"takerdeadline_{label}_closes", "takenWithDeadline", body,
                 f"the taker deadline {label} {'does not close' if label == 'before' else 'closes'} a failed takeover"))

    # ============ E. price and unit-count arithmetic ============
    out.append("\n    // ================= E. arithmetic =================\n\n")
    for ppu in (0, 1, 2, 10**6):
        for units in (1, 2, 3):
            esc = f"{units} * {ppu}" if ppu else "0"
            body = (f"        vm.prank(buyer);\n"
                    f"        uint256 id2 = o.createJob{{value: {esc}}}(executor, {units}, {ppu}, block.timestamp + DAY);\n"
                    f"        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);\n"
                    f"        assertEq(tu, {units});\n        assertEq(p, {ppu});\n        assertEq(e, {esc});\n")
            add(cell(f"escrow_{units}_units_at_price_{ppu}", "open", body,
                     f"escrow for {units} units at price {ppu} is exact"))
    for name, units, ppu in (("huge_units", "type(uint256).max", "2"), ("huge_price", "2", "type(uint256).max"),
                             ("max_both", "type(uint256).max", "type(uint256).max")):
        add(cell(f"escrow_overflow_{name}", "open", (
            f"        vm.prank(buyer);\n"
            f"        vm.expectRevert();\n"
            f"        o.createJob{{value: 0}}(executor, {units}, {ppu}, block.timestamp + DAY);\n"),
            f"overflowing escrow ({name}) panics rather than wrapping"))
    add(cell("escrow_one_wei_short_refused", "open", (
        "        vm.prank(buyer);\n"
        "        vm.expectRevert(abi.encodeWithSelector(Spectral.BadEscrow.selector, ESCROW));\n"
        "        o.createJob{value: ESCROW - 1}(executor, UNITS, PPU, block.timestamp + DAY);\n"),
        "one wei short of the exact escrow is refused"))
    add(cell("escrow_one_wei_over_refused", "open", (
        "        vm.prank(buyer);\n"
        "        vm.expectRevert(abi.encodeWithSelector(Spectral.BadEscrow.selector, ESCROW));\n"
        "        o.createJob{value: ESCROW + 1}(executor, UNITS, PPU, block.timestamp + DAY);\n"),
        "one wei over the exact escrow is refused"))
    add(cell("zero_units_refused", "open", (
        "        vm.prank(buyer);\n"
        "        vm.expectRevert(Spectral.UnitOutOfRange.selector);\n"
        "        o.createJob{value: 0}(executor, 0, PPU, block.timestamp + DAY);\n"),
        "a job with no units cannot exist"))
    add(cell("zero_executor_refused", "open", (
        "        vm.prank(buyer);\n"
        "        vm.expectRevert(Spectral.NotExecutor.selector);\n"
        "        o.createJob{value: ESCROW}(address(0), UNITS, PPU, block.timestamp + DAY);\n"),
        "a job with no executor cannot exist"))

    # ============ F. events ============
    out.append("\n    // ================= F. events =================\n\n")
    add(cell("event_jobcreated", "open", (
        "        vm.prank(buyer);\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.JobCreated(2, buyer, executor, 4, PPU, id);\n"
        "        o.createJob{value: 4 * PPU}(executor, 4, PPU, id);\n"),
        "createJob announces the job"))
    add(cell("event_unitcounted", "open", (
        "        vm.prank(executor);\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.UnitCounted(id, 3, bytes32(uint256(7)), executor);\n"
        "        o.countUnit(id, 3, bytes32(uint256(7)));\n"),
        "counting a unit announces it"))
    add(cell("event_stalled", "open", (
        "        vm.prank(executor);\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.Stalled(id, executor);\n"
        "        o.declareStalled(id);\n"),
        "the stall is announced"))
    add(cell("event_listed", "stalled", (
        "        uint256 dl = block.timestamp + DAY;\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.Listed(id, dl);\n"
        "        o.listObligation(id, dl);\n"),
        "the listing is announced"))
    add(cell("event_taken", "listed", (
        "        uint256 required = o.requiredBond(id);\n"
        "        vm.prank(taker);\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.Taken(id, taker, required);\n"
        "        o.takeObligation{value: required}(id);\n"),
        "the takeover is announced"))
    add(cell("event_settled", "open", (
        "        vm.startPrank(executor);\n"
        "        for (uint256 i; i < UNITS - 1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.Settled(id, ESCROW, 0);\n"
        "        o.countUnit(id, UNITS - 1, bytes32(uint256(99)));\n"
        "        vm.stopPrank();\n"),
        "completion announces settlement with the exact payout"))
    add(cell("event_closed", "takenPartial", (
        "        uint256 bond = o.requiredBond(id);\n"
        "        uint256 remainder = (UNITS - 2) * PPU;\n"
        "        vm.warp(block.timestamp + DAY + 1);\n"
        "        vm.expectEmit(true, true, true, true, address(o));\n"
        "        emit Spectral.Closed(id, remainder + bond, bond);\n"
        "        o.closeFailed(id);\n"),
        "the failure announces the refund and the forfeited bond"))

    # ============ G. isolation between jobs ============
    out.append("\n    // ================= G. isolation =================\n\n")
    add(cell("isolation_two_jobs_are_separate", "open", (
        "        vm.prank(buyer);\n"
        "        uint256 id2 = o.createJob{value: ESCROW}(stranger, UNITS, PPU, block.timestamp + DAY);\n"
        "        assertEq(o.remainingUnits(id), UNITS);\n"
        "        assertEq(o.remainingUnits(id2), UNITS);\n"
        "        vm.prank(executor);\n"
        "        o.countUnit(id, 0, bytes32(uint256(1)));\n"
        "        assertEq(o.remainingUnits(id), UNITS - 1);\n"
        "        assertEq(o.remainingUnits(id2), UNITS);\n"),
        "counting in one job cannot move another"))
    add(cell("isolation_settling_one_leaves_the_other_live", "open", (
        "        vm.prank(buyer);\n"
        "        uint256 id2 = o.createJob{value: ESCROW}(stranger, UNITS, PPU, block.timestamp + DAY);\n"
        "        vm.startPrank(executor);\n"
        "        for (uint256 i; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
        "        vm.stopPrank();\n"
        "        _assertState(id, Spectral.State.Settled);\n"
        "        _assertState(id2, Spectral.State.Open);\n"
        "        assertEq(o.credits(executor), ESCROW);\n"
        "        assertEq(address(o).balance, 2 * ESCROW);\n"),
        "settling one job leaves the other's escrow locked and still in the venue"))
    add(cell("isolation_closing_one_leaves_the_other_live", "takenPartial", (
        "        vm.prank(buyer);\n"
        "        uint256 id2 = o.createJob{value: ESCROW}(stranger, UNITS, PPU, block.timestamp + DAY);\n"
        "        vm.warp(block.timestamp + DAY + 1);\n"
        "        o.closeFailed(id);\n"
        "        _assertState(id2, Spectral.State.Open);\n"),
        "closing one job cannot close another"))
    add(cell("isolation_claim_is_per_account", "closed", (
        "        address[3] memory who = [buyer, executor, taker];\n"
        "        for (uint256 k; k < 3; k++) {\n"
        "            uint256 owed = o.credits(who[k]);\n"
        "            if (owed == 0) {\n"
        "                vm.prank(who[k]);\n"
        "                vm.expectRevert(Spectral.NothingToClaim.selector);\n"
        "                o.claim();\n"
        "            } else {\n"
        "                uint256 before = who[k].balance;\n"
        "                vm.prank(who[k]);\n"
        "                o.claim();\n"
        "                assertEq(who[k].balance - before, owed);\n"
        "                assertEq(o.credits(who[k]), 0);\n"
        "            }\n"
        "        }\n"),
        "each account's credit is its own and is paid exactly once"))
    add(cell("isolation_partial_claim_leaves_others_intact", "closed", (
        "        uint256 buyerOwed = o.credits(buyer);\n"
        "        uint256 execOwed = o.credits(executor);\n"
        "        vm.prank(executor);\n"
        "        o.claim();\n"
        "        assertEq(o.credits(executor), 0);\n"
        "        assertEq(o.credits(buyer), buyerOwed);\n"
        "        assertEq(address(o).balance, buyerOwed);\n"
        "        assertGt(execOwed, 0);\n"),
        "one party claiming leaves the other's credit reserved"))
    add(cell("isolation_second_claim_refused", "closed", (
        "        vm.startPrank(buyer);\n"
        "        o.claim();\n"
        "        vm.expectRevert(Spectral.NothingToClaim.selector);\n"
        "        o.claim();\n"
        "        vm.stopPrank();\n"),
        "a credit cannot be claimed twice"))
    add(cell("isolation_jobcount_monotonic", "open", (
        "        vm.prank(buyer);\n"
        "        uint256 id2 = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);\n"
        "        vm.prank(buyer);\n"
        "        uint256 id3 = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);\n"
        "        assertEq(id2, 2);\n"
        "        assertEq(id3, 3);\n"
        "        assertEq(o.jobCount(), 3);\n"
        "        assertEq(id, 1);\n"),
        "job ids are sequential and never reused"))
    add(cell("isolation_two_takers_one_slot", "listed", (
        "        uint256 required = o.requiredBond(id);\n"
        "        vm.prank(taker);\n"
        "        o.takeObligation{value: required}(id);\n"
        "        vm.prank(stranger);\n"
        "        vm.expectRevert(Spectral.NothingToTake.selector);\n"
        "        o.takeObligation{value: required}(id);\n"),
        "only the first taker can take the obligation"))

    # ============ H. sequences ============
    out.append("\n    // ================= H. sequences =================\n\n")
    for k in range(1, UNITS):
        add(cell(f"sequence_open_after_{k}_units", "open", (
            f"        vm.startPrank(executor);\n"
            f"        for (uint256 i; i < {k}; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
            f"        vm.stopPrank();\n"
            f"        _assertState(id, Spectral.State.Open);\n"
            f"        assertEq(o.remainingUnits(id), {UNITS} - {k});\n"
            f"        assertEq(o.credits(executor), 0);\n"),
            f"{k} of {UNITS} units counted leaves the job open with no payout"))
    add(cell(f"sequence_settles_on_unit_{UNITS}", "open", (
        "        vm.startPrank(executor);\n"
        f"        for (uint256 i; i < {UNITS} - 1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
        "        _assertState(id, Spectral.State.Open);\n"
        f"        o.countUnit(id, {UNITS} - 1, bytes32(uint256(42)));\n"
        "        _assertState(id, Spectral.State.Settled);\n"
        "        assertEq(o.credits(executor), ESCROW);\n"
        "        assertEq(o.remainingUnits(id), 0);\n"
        "        vm.stopPrank();\n"),
        f"the last unit settles, and only the last unit settles"))
    add(cell("sequence_stall_then_list_then_take_then_finish", "open", (
        "        vm.startPrank(executor);\n"
        "        o.countUnit(id, 0, bytes32(uint256(1)));\n"
        "        o.declareStalled(id);\n"
        "        vm.stopPrank();\n"
        "        o.listObligation(id, block.timestamp + DAY);\n"
        "        _assertState(id, Spectral.State.Listed);\n"
        "        uint256 bond = o.requiredBond(id);\n"
        "        vm.prank(taker);\n"
        "        o.takeObligation{value: bond}(id);\n"
        "        _assertState(id, Spectral.State.Taken);\n"
        "        vm.startPrank(taker);\n"
        "        for (uint256 i = 1; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));\n"
        "        vm.stopPrank();\n"
        "        _assertState(id, Spectral.State.Settled);\n"
        "        assertEq(o.credits(executor), PPU);\n"
        "        assertEq(o.credits(taker), (UNITS - 1) * PPU + bond);\n"),
        "the whole continuation path, with each party paid for what it counted"))
    add(cell("sequence_take_then_fail_then_close", "open", (
        "        vm.startPrank(executor);\n"
        "        o.countUnit(id, 0, bytes32(uint256(1)));\n"
        "        o.declareStalled(id);\n"
        "        vm.stopPrank();\n"
        "        o.listObligation(id, block.timestamp + DAY);\n"
        "        uint256 bond = o.requiredBond(id);\n"
        "        vm.prank(taker);\n"
        "        o.takeObligation{value: bond}(id);\n"
        "        vm.warp(block.timestamp + DAY + 1);\n"
        "        o.closeFailed(id);\n"
        "        _assertState(id, Spectral.State.Closed);\n"
        "        assertEq(o.credits(executor), PPU);\n"
        "        assertEq(o.credits(buyer), (UNITS - 1) * PPU + bond);\n"
        "        assertEq(o.credits(taker), 0);\n"),
        "a taker who counts nothing forfeits the bond to the buyer"))

    # ============ I. fuzz ============
    out.append("\n    // ================= I. fuzz =================\n\n")
    out.append('''    /// @dev conservation over arbitrary workloads: sum of credits plus in-flight equals balance
    function testFuzz_matrix_conservation(uint96 escrowUnits, uint256 ppu, uint256 execUnits, uint256 takerUnits) public {
        uint256 units = bound(uint96(escrowUnits), 1, 4);
        ppu = bound(ppu, 0, 1 ether);
        uint256 esc = units * ppu;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, units, ppu, block.timestamp + DAY);

        uint256 e = bound(execUnits, 0, units);
        uint256 t = bound(takerUnits, 0, units - e);
        vm.startPrank(executor);
        for (uint256 i; i < e; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        if (e < units) o.declareStalled(id);
        vm.stopPrank();
        if (e < units) {
            o.listObligation(id, block.timestamp + DAY);
            uint256 bond = o.requiredBond(id);
            vm.prank(taker);
            o.takeObligation{value: bond}(id);
            vm.startPrank(taker);
            for (uint256 i = e; i < e + t; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
            vm.stopPrank();
        }
        uint256 owed = o.credits(buyer) + o.credits(executor) + o.credits(taker);
        uint256 inFlight;
        if (o.stateOf(id) != Spectral.State.Settled) {
            inFlight = esc;
            if (o.stateOf(id) == Spectral.State.Taken) {
                (, , , , , , , , , , uint256 bondHeld, ) = o.jobs(id);
                inFlight += bondHeld;
            }
        }
        assertEq(address(o).balance, owed + inFlight, "conservation broken");
    }

    /// @dev the executor's credit is always exactly what it counted, at any price
    function testFuzz_matrix_executor_paid_for_counted_units(uint128 ppu, uint8 counted) public {
        uint256 price = bound(uint128(ppu), 0, 1 ether);
        uint256 n = bound(uint8(counted), 1, 6);
        uint256 esc = n * price;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, n, price, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < n; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), n * price);
        assertEq(address(o).balance, n * price);
    }

    /// @dev the required bond is always exactly half the remaining escrow
    function testFuzz_matrix_bond_is_half_the_remainder(uint8 total, uint8 counted) public {
        uint256 units = bound(uint8(total), 2, 8);
        uint256 c = bound(uint8(counted), 0, units - 1);
        uint256 price = 1 ether;
        uint256 esc = units * price;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, units, price, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < c; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
        uint256 remaining = units - c;
        assertEq(o.remainingUnits(id), remaining);
        assertEq(o.requiredBond(id), (remaining * price) / 2);
    }

    /// @dev a job can never settle with units outstanding
    function testFuzz_matrix_no_settlement_with_units_outstanding(uint8 counted) public {
        uint256 n = 5;
        uint256 c = bound(uint8(counted), 0, n - 1);
        vm.prank(buyer);
        uint256 id = o.createJob{value: n * PPU}(executor, n, PPU, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < c; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.credits(executor), 0);
        assertEq(address(o).balance, n * PPU);
    }

    /// @dev no sequence of counts can make a party's credit exceed the escrow it is paid from
    function testFuzz_matrix_credits_never_exceed_escrow(uint8 n, uint8 c) public {
        uint256 units = bound(uint8(n), 1, 6);
        uint256 c1 = bound(uint8(c), 0, units);
        uint256 esc = units * PPU;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, units, PPU, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < c1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertLe(o.credits(executor), esc);
        assertLe(o.credits(buyer) + o.credits(executor) + o.credits(taker), esc);
    }
''')
    count += 5

    out.append(FOOTER)
    text = "".join(out)

    # the generated file uses small helpers with explicit setups; add the shapes it references
    helpers = '''
    function _openLate() internal returns (uint256 id) { id = _open(); vm.warp(block.timestamp + DAY + 1); }
    function _stalledLate() internal returns (uint256 id) { id = _stalled(); vm.warp(block.timestamp + DAY + 1); }
    function _listedLate() internal returns (uint256 id) { id = _listed(); vm.warp(block.timestamp + DAY + 1); }
    function _takenLate() internal returns (uint256 id) { id = _taken(); vm.warp(block.timestamp + DAY + 1); }
    function _takenPartialLate() internal returns (uint256 id) { id = _takenPartial(); vm.warp(block.timestamp + DAY + 1); }
    function _settledLate() internal returns (uint256 id) { id = _settled(); vm.warp(block.timestamp + DAY + 1); }
    function _closedLate() internal returns (uint256 id) { id = _closed(); vm.warp(block.timestamp + DAY + 1); }

    /// @dev a job with `remaining` units left, stalled and listed
    function _open20() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: 20 * PPU}(executor, 20, PPU, block.timestamp + DAY);
    }

    function _partial(uint256 remaining) internal returns (uint256 id) {
        id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < UNITS - remaining; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
    }

    function _partial0() internal returns (uint256 id) { return _partial(0); }
    function _partial1() internal returns (uint256 id) { return _partial(1); }
    function _partial2() internal returns (uint256 id) { return _partial(2); }
    function _partial3() internal returns (uint256 id) { return _partial(3); }
    function _partial4() internal returns (uint256 id) { return _partial(4); }
    function _partial5() internal returns (uint256 id) { return _partial(5); }
    function _partial6() internal returns (uint256 id) { return _partial(6); }
    function _partial7() internal returns (uint256 id) { return _partial(7); }
    function _partial8() internal returns (uint256 id) { return _partial(8); }
    function _partial9() internal returns (uint256 id) { return _partial(9); }
    function _partial10() internal returns (uint256 id) { return _partial(10); }
    function _partial11() internal returns (uint256 id) { return _partial(11); }
    function _partial12() internal returns (uint256 id) { return _partial(12); }
    function _partial13() internal returns (uint256 id) { return _partial(13); }
    function _partial14() internal returns (uint256 id) { return _partial(14); }
    function _partial15() internal returns (uint256 id) { return _partial(15); }
    function _partial16() internal returns (uint256 id) { return _partial(16); }
    function _partial17() internal returns (uint256 id) { return _partial(17); }
    function _partial18() internal returns (uint256 id) { return _partial(18); }
    function _partial19() internal returns (uint256 id) { return _partial(19); }
    function _partial20() internal returns (uint256 id) { return _partial(20); }

    function _openWithDeadline() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
        workDeadlineOverride = block.timestamp + DAY;
    }

    function _takenWithDeadline() internal returns (uint256 id) {
        id = _takenPartial();
        takerDeadlineOverride = block.timestamp + DAY;
    }
'''
    # splice helpers in before _assertState
    text = text.replace("    function _assertState(", helpers + "\n    function _assertState(")
    # the deadline tests need the deadline values; capture them in the tests instead
    text = text.replace("""    function _openWithDeadline() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
        workDeadlineOverride = block.timestamp + DAY;
    }

    function _takenWithDeadline() internal returns (uint256 id) {
        id = _takenPartial();
        takerDeadlineOverride = block.timestamp + DAY;
    }""", """    function _openWithDeadline() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
    }

    function _takenWithDeadline() internal returns (uint256 id) {
        id = _takenPartial();
    }""")
    text = text.replace("id_workDeadline", "workDeadline")
    text = text.replace("takerDeadline - 1", "takerDeadlineOf(id) - 1")
    
    # deadline boundary tests reference helpers that read the struct
    extra_helpers = '''
    function workDeadlineOf(uint256 id) internal view returns (uint256 d) {
        (, , , , , , , d, , , , ) = o.jobs(id);
    }

    function takerDeadlineOf(uint256 id) internal view returns (uint256 d) {
        (, , , , , , , , d, , , ) = o.jobs(id);
    }
'''
    text = text.replace("\n    function _assertState(", extra_helpers + "\n    function _assertState(")

    pathlib.Path("test/SpectralMatrix.t.sol").write_text(text)
    print(f"generated test/SpectralMatrix.t.sol with {count} matrix tests")


if __name__ == "__main__":
    main()
