// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {Spectral} from "../src/Spectral.sol";

/// @title SpectralMatrix — conformance matrix over states x operations x actors
/// @notice GENERATED by test/gen_matrix_tests.py — edit the generator, not this file.
/// Each test asserts the exact error selector or the exact resulting state, so a
/// weakened guard in any state fails a named cell.
contract SpectralMatrixTest is Test {
    Spectral o;

    address buyer = address(0xB0B);
    address executor = address(0xE0E);
    address taker = address(0x7A4E);
    address stranger = address(0x57A);

    uint256 constant UNITS = 10;
    uint256 constant PPU = 1 ether;
    uint256 constant ESCROW = UNITS * PPU;
    uint256 constant DAY = 1 days;

    function setUp() public {
        o = new Spectral();
        vm.deal(buyer, 10_000 ether);
        vm.deal(executor, 10_000 ether);
        vm.deal(taker, 10_000 ether);
        vm.deal(stranger, 10_000 ether);
    }

    // ---------- state construction, through the public API only ----------

    function _open() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
    }

    function _stalled() internal returns (uint256 id) {
        id = _open();
        vm.prank(executor);
        o.declareStalled(id);
    }

    function _listed() internal returns (uint256 id) {
        id = _stalled();
        o.listObligation(id, block.timestamp + DAY);
    }

    function _taken() internal returns (uint256 id) {
        id = _listed();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertTakerIsRecorded(id, taker);
    }

    /// @dev two units counted, then the executor quits and a taker posts the bond
    function _takenPartial() internal returns (uint256 id) {
        id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 0, bytes32(uint256(1)));
        o.countUnit(id, 1, bytes32(uint256(2)));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
    }

    function _settled() internal returns (uint256 id) {
        id = _open();
        for (uint256 i; i < UNITS; i++) {
            vm.prank(executor);
            o.countUnit(id, i, bytes32(uint256(i) + 1));
        }
    }

    function _closed() internal returns (uint256 id) {
        id = _takenPartial();
        vm.warp(block.timestamp + DAY + 1);
        o.closeFailed(id);
    }


    function _openLate() internal returns (uint256 id) { id = _open(); vm.warp(block.timestamp + DAY + 1); }
    function _stalledLate() internal returns (uint256 id) { id = _stalled(); vm.warp(block.timestamp + DAY + 1); }
    function _listedLate() internal returns (uint256 id) { id = _listed(); vm.warp(block.timestamp + DAY + 1); }
    function _takenLate() internal returns (uint256 id) { id = _taken(); vm.warp(block.timestamp + DAY + 1); }
    function _takenPartialLate() internal returns (uint256 id) { id = _takenPartial(); vm.warp(block.timestamp + DAY + 1); }
    function _settledLate() internal returns (uint256 id) { id = _settled(); vm.warp(block.timestamp + DAY + 1); }
    function _closedLate() internal returns (uint256 id) { id = _closed(); vm.warp(block.timestamp + DAY + 1); }

    /// @dev a job with `remaining` units left, stalled and listed
    function _open20() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: 20 * PPU}(executor, 20, PPU, block.timestamp + DAY);
    }

    function _partial(uint256 remaining) internal returns (uint256 id) {
        id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < UNITS - remaining; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
    }

    function _partial0() internal returns (uint256 id) { return _partial(0); }
    function _partial1() internal returns (uint256 id) { return _partial(1); }
    function _partial2() internal returns (uint256 id) { return _partial(2); }
    function _partial3() internal returns (uint256 id) { return _partial(3); }
    function _partial4() internal returns (uint256 id) { return _partial(4); }
    function _partial5() internal returns (uint256 id) { return _partial(5); }
    function _partial6() internal returns (uint256 id) { return _partial(6); }
    function _partial7() internal returns (uint256 id) { return _partial(7); }
    function _partial8() internal returns (uint256 id) { return _partial(8); }
    function _partial9() internal returns (uint256 id) { return _partial(9); }
    function _partial10() internal returns (uint256 id) { return _partial(10); }
    function _partial11() internal returns (uint256 id) { return _partial(11); }
    function _partial12() internal returns (uint256 id) { return _partial(12); }
    function _partial13() internal returns (uint256 id) { return _partial(13); }
    function _partial14() internal returns (uint256 id) { return _partial(14); }
    function _partial15() internal returns (uint256 id) { return _partial(15); }
    function _partial16() internal returns (uint256 id) { return _partial(16); }
    function _partial17() internal returns (uint256 id) { return _partial(17); }
    function _partial18() internal returns (uint256 id) { return _partial(18); }
    function _partial19() internal returns (uint256 id) { return _partial(19); }
    function _partial20() internal returns (uint256 id) { return _partial(20); }

    function _openWithDeadline() internal returns (uint256 id) {
        vm.prank(buyer);
        id = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
    }

    function _takenWithDeadline() internal returns (uint256 id) {
        id = _takenPartial();
    }

    function workDeadlineOf(uint256 id) internal view returns (uint256 d) {
        (, , , , , , , d, , , , ) = o.jobs(id);
    }

    function takerDeadlineOf(uint256 id) internal view returns (uint256 d) {
        (, , , , , , , , d, , , ) = o.jobs(id);
    }

    function _assertState(uint256 id, Spectral.State want) internal view {
        assertEq(uint256(o.stateOf(id)), uint256(want), "state mismatch");
    }

    /// @dev a setup that took the obligation must have recorded THIS contract's taker,
    /// not the test contract: a view call inside a pranked call's arguments eats the prank.
    function _assertTakerIsRecorded(uint256 id, address who) internal view {
        (, , , , , , , , , address recorded, , ) = o.jobs(id);
        assertEq(recorded, who, "the recorded taker is not the intended taker");
    }

    // ================= A. states x operations x actors =================

    // ---------- from Open ----------

    /// @dev from open: countByExecutor
    function test_matrix_open_countByExecutor() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 9, bytes32(uint256(0xABC)));
        _assertState(id, Spectral.State.Open);
    }
    /// @dev from open: countByTaker
    function test_matrix_open_countByTaker() public {
        uint256 id = _open();
        vm.prank(taker);
        vm.expectRevert(Spectral.NotExecutor.selector);
        o.countUnit(id, 9, bytes32(uint256(0xABC)));
    }
    /// @dev from open: countByStranger
    function test_matrix_open_countByStranger() public {
        uint256 id = _open();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NotExecutor.selector);
        o.countUnit(id, 9, bytes32(uint256(0xABC)));
    }
    /// @dev from open: stallByExecutor
    function test_matrix_open_stallByExecutor() public {
        uint256 id = _open();
        vm.prank(executor);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev from open: stallByStrangerEarly
    function test_matrix_open_stallByStrangerEarly() public {
        uint256 id = _open();
        vm.prank(stranger);
        vm.expectRevert(Spectral.DeadlineNotReached.selector);
        o.declareStalled(id);
    }
    /// @dev from open, past the work deadline: stallByStrangerLate
    function test_matrix_open_stallByStrangerLate() public {
        uint256 id = _openLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev from open: listFromOpen
    function test_matrix_open_listFromOpen() public {
        uint256 id = _open();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.listObligation(id, block.timestamp + DAY);
    }
    /// @dev from open: takeFromOpen
    function test_matrix_open_takeFromOpen() public {
        uint256 id = _open();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: required}(id);
    }
    /// @dev from open: takeUnderBondFromOpen
    function test_matrix_open_takeUnderBondFromOpen() public {
        uint256 id = _open();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: 1}(id);
    }
    /// @dev from open: closeEarlyFromOpen
    function test_matrix_open_closeEarlyFromOpen() public {
        uint256 id = _open();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from open, past the work deadline: closeLateFromOpen
    function test_matrix_open_closeLateFromOpen() public {
        uint256 id = _openLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from open: claimByExecutorFromOpen
    function test_matrix_open_claimByExecutorFromOpen() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from open: claimByBuyerFromOpen
    function test_matrix_open_claimByBuyerFromOpen() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from open: claimByTakerFromOpen
    function test_matrix_open_claimByTakerFromOpen() public {
        uint256 id = _open();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    // ---------- from Stalled ----------

    /// @dev from stalled: countByExecutor
    function test_matrix_stalled_countByExecutor() public {
        uint256 id = _stalled();
        vm.prank(executor);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from stalled: countByTaker
    function test_matrix_stalled_countByTaker() public {
        uint256 id = _stalled();
        vm.prank(taker);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from stalled: countByStranger
    function test_matrix_stalled_countByStranger() public {
        uint256 id = _stalled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from stalled: stallByExecutor
    function test_matrix_stalled_stallByExecutor() public {
        uint256 id = _stalled();
        vm.prank(executor);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from stalled: stallByStrangerEarly
    function test_matrix_stalled_stallByStrangerEarly() public {
        uint256 id = _stalled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from stalled, past the deadline: stallByStrangerLate
    function test_matrix_stalled_stallByStrangerLate() public {
        uint256 id = _stalledLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from stalled: listFromStalled
    function test_matrix_stalled_listFromStalled() public {
        uint256 id = _stalled();
        vm.prank(stranger);
        o.listObligation(id, block.timestamp + DAY);
        _assertState(id, Spectral.State.Listed);
    }
    /// @dev from stalled: takeFromStalled
    function test_matrix_stalled_takeFromStalled() public {
        uint256 id = _stalled();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: required}(id);
    }
    /// @dev from stalled: takeUnderBondFromStalled
    function test_matrix_stalled_takeUnderBondFromStalled() public {
        uint256 id = _stalled();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: 1}(id);
    }
    /// @dev from stalled: closeEarlyFromStalled
    function test_matrix_stalled_closeEarlyFromStalled() public {
        uint256 id = _stalled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from stalled, past the deadline: closeLateFromStalled
    function test_matrix_stalled_closeLateFromStalled() public {
        uint256 id = _stalledLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from stalled: claimByExecutorFromStalled
    function test_matrix_stalled_claimByExecutorFromStalled() public {
        uint256 id = _stalled();
        vm.prank(executor);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from stalled: claimByBuyerFromStalled
    function test_matrix_stalled_claimByBuyerFromStalled() public {
        uint256 id = _stalled();
        vm.prank(buyer);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from stalled: claimByTakerFromStalled
    function test_matrix_stalled_claimByTakerFromStalled() public {
        uint256 id = _stalled();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    // ---------- from Listed ----------

    /// @dev from listed: countByExecutor
    function test_matrix_listed_countByExecutor() public {
        uint256 id = _listed();
        vm.prank(executor);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from listed: countByTaker
    function test_matrix_listed_countByTaker() public {
        uint256 id = _listed();
        vm.prank(taker);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from listed: countByStranger
    function test_matrix_listed_countByStranger() public {
        uint256 id = _listed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from listed: stallByExecutor
    function test_matrix_listed_stallByExecutor() public {
        uint256 id = _listed();
        vm.prank(executor);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from listed: stallByStrangerEarly
    function test_matrix_listed_stallByStrangerEarly() public {
        uint256 id = _listed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from listed, past the deadline: stallByStrangerLate
    function test_matrix_listed_stallByStrangerLate() public {
        uint256 id = _listedLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from listed: listFromListed
    function test_matrix_listed_listFromListed() public {
        uint256 id = _listed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.listObligation(id, block.timestamp + DAY);
    }
    /// @dev from listed: takeFromListed
    function test_matrix_listed_takeFromListed() public {
        uint256 id = _listed();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
    }
    /// @dev from listed: takeUnderBondFromListed
    function test_matrix_listed_takeUnderBondFromListed() public {
        uint256 id = _listed();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev from listed: closeEarlyFromListed
    function test_matrix_listed_closeEarlyFromListed() public {
        uint256 id = _listed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from listed, past the deadline: closeLateFromListed
    function test_matrix_listed_closeLateFromListed() public {
        uint256 id = _listedLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from listed: claimByExecutorFromListed
    function test_matrix_listed_claimByExecutorFromListed() public {
        uint256 id = _listed();
        vm.prank(executor);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from listed: claimByBuyerFromListed
    function test_matrix_listed_claimByBuyerFromListed() public {
        uint256 id = _listed();
        vm.prank(buyer);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from listed: claimByTakerFromListed
    function test_matrix_listed_claimByTakerFromListed() public {
        uint256 id = _listed();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    // ---------- from Taken ----------

    /// @dev from taken: countByTaker
    function test_matrix_taken_countByTaker() public {
        uint256 id = _taken();
        vm.prank(taker);
        o.countUnit(id, 9, bytes32(uint256(1)));
        _assertState(id, Spectral.State.Taken);
    }
    /// @dev from taken: countByExecutor
    function test_matrix_taken_countByExecutor() public {
        uint256 id = _taken();
        vm.prank(executor);
        vm.expectRevert(Spectral.NotExecutor.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from taken: countByStranger
    function test_matrix_taken_countByStranger() public {
        uint256 id = _taken();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NotExecutor.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from taken: stallByExecutor
    function test_matrix_taken_stallByExecutor() public {
        uint256 id = _taken();
        vm.prank(executor);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from taken: stallByStrangerEarly
    function test_matrix_taken_stallByStrangerEarly() public {
        uint256 id = _taken();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from taken, past the deadline: stallByStrangerLate
    function test_matrix_taken_stallByStrangerLate() public {
        uint256 id = _takenLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from taken: listFromTaken
    function test_matrix_taken_listFromTaken() public {
        uint256 id = _taken();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.listObligation(id, block.timestamp + DAY);
    }
    /// @dev from taken: takeFromTaken
    function test_matrix_taken_takeFromTaken() public {
        uint256 id = _taken();
        uint256 required = o.requiredBond(id);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: required}(id);
    }
    /// @dev from taken: takeUnderBondFromTaken
    function test_matrix_taken_takeUnderBondFromTaken() public {
        uint256 id = _taken();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: 1}(id);
    }
    /// @dev from taken: closeEarlyFromTaken
    function test_matrix_taken_closeEarlyFromTaken() public {
        uint256 id = _taken();
        vm.prank(stranger);
        vm.expectRevert(Spectral.DeadlineNotReached.selector);
        o.closeFailed(id);
    }
    /// @dev from taken with units outstanding, past the taker deadline: closeLateFromTaken
    function test_matrix_taken_closeLateFromTaken() public {
        uint256 id = _takenPartialLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        o.closeFailed(id);
        _assertState(id, Spectral.State.Closed);
    }
    /// @dev from taken: claimByExecutorFromTaken
    function test_matrix_taken_claimByExecutorFromTaken() public {
        uint256 id = _taken();
        vm.prank(executor);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from taken: claimByBuyerFromTaken
    function test_matrix_taken_claimByBuyerFromTaken() public {
        uint256 id = _taken();
        vm.prank(buyer);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from taken: claimByTakerFromTaken
    function test_matrix_taken_claimByTakerFromTaken() public {
        uint256 id = _taken();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    // ---------- from Settled ----------

    /// @dev from settled: countByExecutorFromSettled
    function test_matrix_settled_countByExecutorFromSettled() public {
        uint256 id = _settled();
        vm.prank(executor);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from settled: countByTakerFromSettled
    function test_matrix_settled_countByTakerFromSettled() public {
        uint256 id = _settled();
        vm.prank(taker);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from settled: countByStrangerFromSettled
    function test_matrix_settled_countByStrangerFromSettled() public {
        uint256 id = _settled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from settled: stallByExecutorFromSettled
    function test_matrix_settled_stallByExecutorFromSettled() public {
        uint256 id = _settled();
        vm.prank(executor);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from settled: stallByStrangerEarlyFromSettled
    function test_matrix_settled_stallByStrangerEarlyFromSettled() public {
        uint256 id = _settled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from settled, past the deadline: stallByStrangerLateFromSettled
    function test_matrix_settled_stallByStrangerLateFromSettled() public {
        uint256 id = _settledLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from settled: listFromSettled
    function test_matrix_settled_listFromSettled() public {
        uint256 id = _settled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.listObligation(id, block.timestamp + DAY);
    }
    /// @dev from settled: takeFromSettled
    function test_matrix_settled_takeFromSettled() public {
        uint256 id = _settled();
        uint256 required = o.requiredBond(id);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: required}(id);
    }
    /// @dev from settled: takeUnderBondFromSettled
    function test_matrix_settled_takeUnderBondFromSettled() public {
        uint256 id = _settled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: 1}(id);
    }
    /// @dev from settled: closeEarlyFromSettled
    function test_matrix_settled_closeEarlyFromSettled() public {
        uint256 id = _settled();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from settled, past the deadline: closeLateFromSettled
    function test_matrix_settled_closeLateFromSettled() public {
        uint256 id = _settledLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from settled: claimByExecutorFromSettled
    function test_matrix_settled_claimByExecutorFromSettled() public {
        uint256 id = _settled();
        uint256 owed = o.credits(executor);
        uint256 before = executor.balance;
        vm.prank(executor);
        o.claim();
        assertEq(executor.balance - before, owed);
        assertEq(o.credits(executor), 0);
    }
    /// @dev from settled: claimByBuyerFromSettled
    function test_matrix_settled_claimByBuyerFromSettled() public {
        uint256 id = _settled();
        vm.prank(buyer);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    /// @dev from settled: claimByTakerFromSettled
    function test_matrix_settled_claimByTakerFromSettled() public {
        uint256 id = _settled();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }
    // ---------- from Closed ----------

    /// @dev from closed: countByExecutorFromClosed
    function test_matrix_closed_countByExecutorFromClosed() public {
        uint256 id = _closed();
        vm.prank(executor);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from closed: countByTakerFromClosed
    function test_matrix_closed_countByTakerFromClosed() public {
        uint256 id = _closed();
        vm.prank(taker);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from closed: countByStrangerFromClosed
    function test_matrix_closed_countByStrangerFromClosed() public {
        uint256 id = _closed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.JobNotOpen.selector);
        o.countUnit(id, 9, bytes32(uint256(1)));
    }
    /// @dev from closed: stallByExecutorFromClosed
    function test_matrix_closed_stallByExecutorFromClosed() public {
        uint256 id = _closed();
        vm.prank(executor);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from closed: stallByStrangerEarlyFromClosed
    function test_matrix_closed_stallByStrangerEarlyFromClosed() public {
        uint256 id = _closed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from closed, past the deadline: stallByStrangerLateFromClosed
    function test_matrix_closed_stallByStrangerLateFromClosed() public {
        uint256 id = _closedLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.declareStalled(id);
    }
    /// @dev from closed: listFromClosed
    function test_matrix_closed_listFromClosed() public {
        uint256 id = _closed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.AlreadyStalled.selector);
        o.listObligation(id, block.timestamp + DAY);
    }
    /// @dev from closed: takeFromClosed
    function test_matrix_closed_takeFromClosed() public {
        uint256 id = _closed();
        uint256 required = o.requiredBond(id);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: required}(id);
    }
    /// @dev from closed: takeUnderBondFromClosed
    function test_matrix_closed_takeUnderBondFromClosed() public {
        uint256 id = _closed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: 1}(id);
    }
    /// @dev from closed: closeEarlyFromClosed
    function test_matrix_closed_closeEarlyFromClosed() public {
        uint256 id = _closed();
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from closed, past the deadline: closeLateFromClosed
    function test_matrix_closed_closeLateFromClosed() public {
        uint256 id = _closedLate();
        vm.warp(block.timestamp + DAY + 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.closeFailed(id);
    }
    /// @dev from closed: claimByExecutorFromClosed
    function test_matrix_closed_claimByExecutorFromClosed() public {
        uint256 id = _closed();
        uint256 owed = o.credits(executor);
        uint256 before = executor.balance;
        vm.prank(executor);
        o.claim();
        assertEq(executor.balance - before, owed);
        assertEq(o.credits(executor), 0);
    }
    /// @dev from closed: claimByBuyerFromClosed
    function test_matrix_closed_claimByBuyerFromClosed() public {
        uint256 id = _closed();
        uint256 owed = o.credits(buyer);
        uint256 before = buyer.balance;
        vm.prank(buyer);
        o.claim();
        assertEq(buyer.balance - before, owed);
        assertEq(o.credits(buyer), 0);
    }
    /// @dev from closed: claimByTakerFromClosed
    function test_matrix_closed_claimByTakerFromClosed() public {
        uint256 id = _closed();
        vm.prank(taker);
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
    }

    // ================= B. unit index boundary =================

    /// @dev index 0 is inside the unit range
    function test_index_0_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 0, bytes32(uint256(0) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 1 is inside the unit range
    function test_index_1_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 1, bytes32(uint256(1) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 2 is inside the unit range
    function test_index_2_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 2, bytes32(uint256(2) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 3 is inside the unit range
    function test_index_3_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 3, bytes32(uint256(3) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 4 is inside the unit range
    function test_index_4_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 4, bytes32(uint256(4) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 5 is inside the unit range
    function test_index_5_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 5, bytes32(uint256(5) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 6 is inside the unit range
    function test_index_6_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 6, bytes32(uint256(6) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 7 is inside the unit range
    function test_index_7_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 7, bytes32(uint256(7) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 8 is inside the unit range
    function test_index_8_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 8, bytes32(uint256(8) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 9 is inside the unit range
    function test_index_9_countable() public {
        uint256 id = _open();
        vm.prank(executor);
        o.countUnit(id, 9, bytes32(uint256(9) + 1));
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev index 10 is outside the unit range
    function test_index_10_refused() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, 10, bytes32(uint256(1)));
    }
    /// @dev index 11 is outside the unit range
    function test_index_11_refused() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, 11, bytes32(uint256(1)));
    }
    /// @dev index 255 is outside the unit range
    function test_index_255_refused() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, 255, bytes32(uint256(1)));
    }
    /// @dev index type(uint256).max is outside the unit range
    function test_index_uint256_max_refused() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, type(uint256).max, bytes32(uint256(1)));
    }
    /// @dev unit 0 cannot be counted twice
    function test_index_0_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 0, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 0, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 1 cannot be counted twice
    function test_index_1_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 1, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 1, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 2 cannot be counted twice
    function test_index_2_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 2, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 2, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 3 cannot be counted twice
    function test_index_3_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 3, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 3, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 4 cannot be counted twice
    function test_index_4_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 4, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 4, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 5 cannot be counted twice
    function test_index_5_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 5, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 5, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 6 cannot be counted twice
    function test_index_6_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 6, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 6, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 7 cannot be counted twice
    function test_index_7_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 7, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 7, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 8 cannot be counted twice
    function test_index_8_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 8, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 8, bytes32(uint256(2)));
        vm.stopPrank();
    }
    /// @dev unit 9 cannot be counted twice
    function test_index_9_duplicate_refused() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 9, bytes32(uint256(1)));
        vm.expectRevert(Spectral.UnitAlreadyCounted.selector);
        o.countUnit(id, 9, bytes32(uint256(2)));
        vm.stopPrank();
    }

    // ================= B2. wider unit range =================

    /// @dev index 0 is countable in a twenty-unit job
    function test_wide_index_0_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 0, bytes32(uint256(0) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 1 is countable in a twenty-unit job
    function test_wide_index_1_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 1, bytes32(uint256(1) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 2 is countable in a twenty-unit job
    function test_wide_index_2_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 2, bytes32(uint256(2) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 3 is countable in a twenty-unit job
    function test_wide_index_3_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 3, bytes32(uint256(3) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 4 is countable in a twenty-unit job
    function test_wide_index_4_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 4, bytes32(uint256(4) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 5 is countable in a twenty-unit job
    function test_wide_index_5_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 5, bytes32(uint256(5) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 6 is countable in a twenty-unit job
    function test_wide_index_6_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 6, bytes32(uint256(6) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 7 is countable in a twenty-unit job
    function test_wide_index_7_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 7, bytes32(uint256(7) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 8 is countable in a twenty-unit job
    function test_wide_index_8_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 8, bytes32(uint256(8) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 9 is countable in a twenty-unit job
    function test_wide_index_9_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 9, bytes32(uint256(9) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 10 is countable in a twenty-unit job
    function test_wide_index_10_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 10, bytes32(uint256(10) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 11 is countable in a twenty-unit job
    function test_wide_index_11_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 11, bytes32(uint256(11) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 12 is countable in a twenty-unit job
    function test_wide_index_12_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 12, bytes32(uint256(12) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 13 is countable in a twenty-unit job
    function test_wide_index_13_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 13, bytes32(uint256(13) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 14 is countable in a twenty-unit job
    function test_wide_index_14_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 14, bytes32(uint256(14) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 15 is countable in a twenty-unit job
    function test_wide_index_15_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 15, bytes32(uint256(15) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 16 is countable in a twenty-unit job
    function test_wide_index_16_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 16, bytes32(uint256(16) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 17 is countable in a twenty-unit job
    function test_wide_index_17_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 17, bytes32(uint256(17) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 18 is countable in a twenty-unit job
    function test_wide_index_18_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 18, bytes32(uint256(18) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 19 is countable in a twenty-unit job
    function test_wide_index_19_countable() public {
        uint256 id = _open20();
        vm.prank(executor);
        o.countUnit(id, 19, bytes32(uint256(19) + 1));
        assertEq(o.remainingUnits(id), 20 - 1);
    }
    /// @dev index 20 is refused in a twenty-unit job
    function test_wide_index_20_refused() public {
        uint256 id = _open20();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, 20, bytes32(uint256(1)));
    }
    /// @dev index 21 is refused in a twenty-unit job
    function test_wide_index_21_refused() public {
        uint256 id = _open20();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, 21, bytes32(uint256(1)));
    }
    /// @dev index 1024 is refused in a twenty-unit job
    function test_wide_index_1024_refused() public {
        uint256 id = _open20();
        vm.prank(executor);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.countUnit(id, 1024, bytes32(uint256(1)));
    }

    // ================= C. bond boundary =================

    /// @dev exact bond accepted with 1 units remaining
    function test_bond_exact_1_units_remain() public {
        uint256 id = _partial1();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 1 units remaining
    function test_bond_one_wei_short_1_units_remain() public {
        uint256 id = _partial1();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 1 units remaining
    function test_bond_overpay_1_units_remain() public {
        uint256 id = _partial1();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 1 units remaining
    function test_bond_formula_1_units_remain() public {
        uint256 id = _partial1();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }
    /// @dev exact bond accepted with 2 units remaining
    function test_bond_exact_2_units_remain() public {
        uint256 id = _partial2();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 2 units remaining
    function test_bond_one_wei_short_2_units_remain() public {
        uint256 id = _partial2();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 2 units remaining
    function test_bond_overpay_2_units_remain() public {
        uint256 id = _partial2();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 2 units remaining
    function test_bond_formula_2_units_remain() public {
        uint256 id = _partial2();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }
    /// @dev exact bond accepted with 3 units remaining
    function test_bond_exact_3_units_remain() public {
        uint256 id = _partial3();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 3 units remaining
    function test_bond_one_wei_short_3_units_remain() public {
        uint256 id = _partial3();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 3 units remaining
    function test_bond_overpay_3_units_remain() public {
        uint256 id = _partial3();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 3 units remaining
    function test_bond_formula_3_units_remain() public {
        uint256 id = _partial3();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }
    /// @dev exact bond accepted with 4 units remaining
    function test_bond_exact_4_units_remain() public {
        uint256 id = _partial4();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 4 units remaining
    function test_bond_one_wei_short_4_units_remain() public {
        uint256 id = _partial4();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 4 units remaining
    function test_bond_overpay_4_units_remain() public {
        uint256 id = _partial4();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 4 units remaining
    function test_bond_formula_4_units_remain() public {
        uint256 id = _partial4();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }
    /// @dev exact bond accepted with 5 units remaining
    function test_bond_exact_5_units_remain() public {
        uint256 id = _partial5();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 5 units remaining
    function test_bond_one_wei_short_5_units_remain() public {
        uint256 id = _partial5();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 5 units remaining
    function test_bond_overpay_5_units_remain() public {
        uint256 id = _partial5();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 5 units remaining
    function test_bond_formula_5_units_remain() public {
        uint256 id = _partial5();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }
    /// @dev exact bond accepted with 6 units remaining
    function test_bond_exact_6_units_remain() public {
        uint256 id = _partial6();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 6 units remaining
    function test_bond_one_wei_short_6_units_remain() public {
        uint256 id = _partial6();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 6 units remaining
    function test_bond_overpay_6_units_remain() public {
        uint256 id = _partial6();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 6 units remaining
    function test_bond_formula_6_units_remain() public {
        uint256 id = _partial6();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }
    /// @dev exact bond accepted with 7 units remaining
    function test_bond_exact_7_units_remain() public {
        uint256 id = _partial7();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        _assertState(id, Spectral.State.Taken);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required);
    }
    /// @dev one wei short of the bond is refused with 7 units remaining
    function test_bond_one_wei_short_7_units_remain() public {
        uint256 id = _partial7();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BondTooSmall.selector, required));
        o.takeObligation{value: required - 1}(id);
    }
    /// @dev an overpaid bond is recorded in full with 7 units remaining
    function test_bond_overpay_7_units_remain() public {
        uint256 id = _partial7();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required + 1}(id);
        (, , , , , , , , , , uint256 bond, ) = o.jobs(id);
        assertEq(bond, required + 1);
    }
    /// @dev the bond is exactly half the remaining escrow with 7 units remaining
    function test_bond_formula_7_units_remain() public {
        uint256 id = _partial7();
        uint256 remaining_units = o.remainingUnits(id);
        assertEq(o.requiredBond(id), (remaining_units * PPU * 5000) / 10000);
    }

    // ================= E2. payout and remainder exactness =================

    /// @dev after 1 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_1_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 1);
    }
    /// @dev a split of 2 and 8 units pays each side for exactly what it counted
    function test_settled_for_1_units_pays_1_times_price() public {
        uint256 id = _partial8();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 8; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 2 * PPU);
        assertEq(o.credits(taker), 8 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 2 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_2_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 2; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 2);
    }
    /// @dev a split of 3 and 7 units pays each side for exactly what it counted
    function test_settled_for_2_units_pays_2_times_price() public {
        uint256 id = _partial7();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 7; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 3 * PPU);
        assertEq(o.credits(taker), 7 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 3 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_3_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 3; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 3);
    }
    /// @dev a split of 4 and 6 units pays each side for exactly what it counted
    function test_settled_for_3_units_pays_3_times_price() public {
        uint256 id = _partial6();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 6; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 4 * PPU);
        assertEq(o.credits(taker), 6 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 4 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_4_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 4; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 4);
    }
    /// @dev a split of 5 and 5 units pays each side for exactly what it counted
    function test_settled_for_4_units_pays_4_times_price() public {
        uint256 id = _partial5();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 5; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 5 * PPU);
        assertEq(o.credits(taker), 5 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 5 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_5_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 5; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 5);
    }
    /// @dev a split of 6 and 4 units pays each side for exactly what it counted
    function test_settled_for_5_units_pays_5_times_price() public {
        uint256 id = _partial4();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 4; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 6 * PPU);
        assertEq(o.credits(taker), 4 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 6 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_6_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 6; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 6);
    }
    /// @dev a split of 7 and 3 units pays each side for exactly what it counted
    function test_settled_for_6_units_pays_6_times_price() public {
        uint256 id = _partial3();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 3; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 7 * PPU);
        assertEq(o.credits(taker), 3 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 7 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_7_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 7; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 7);
    }
    /// @dev a split of 8 and 2 units pays each side for exactly what it counted
    function test_settled_for_7_units_pays_7_times_price() public {
        uint256 id = _partial2();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 2; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 8 * PPU);
        assertEq(o.credits(taker), 2 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }
    /// @dev after 8 units: nothing is owed yet and the remainder is exact
    function test_paid_exactly_for_8_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 8; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), 0);
        assertEq(o.remainingUnits(id), UNITS - 8);
    }
    /// @dev a split of 9 and 1 units pays each side for exactly what it counted
    function test_settled_for_8_units_pays_8_times_price() public {
        uint256 id = _partial1();
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertTakerIsRecorded(id, taker);
        vm.startPrank(taker);
        for (uint256 i = UNITS - 1; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), 9 * PPU);
        assertEq(o.credits(taker), 1 * PPU + bond);
        assertEq(address(o).balance, o.credits(executor) + o.credits(taker));
    }

    // ================= D. deadline boundary =================

    /// @dev the work deadline before: executor may stall
    function test_workdeadline_before_by_executor() public {
        uint256 id = _openWithDeadline();
        uint256 workDeadline = workDeadlineOf(id);
        vm.warp(workDeadline - 1);
        vm.prank(executor);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev the work deadline before: stranger may not stall
    function test_workdeadline_before_by_stranger() public {
        uint256 id = _openWithDeadline();
        uint256 workDeadline = workDeadlineOf(id);
        vm.warp(workDeadline - 1);
        vm.prank(stranger);
        vm.expectRevert(Spectral.DeadlineNotReached.selector);
        o.declareStalled(id);
    }
    /// @dev the work deadline exactly_at: executor may stall
    function test_workdeadline_exactly_at_by_executor() public {
        uint256 id = _openWithDeadline();
        uint256 workDeadline = workDeadlineOf(id);
        vm.warp(workDeadline);
        vm.prank(executor);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev the work deadline exactly_at: stranger may stall
    function test_workdeadline_exactly_at_by_stranger() public {
        uint256 id = _openWithDeadline();
        uint256 workDeadline = workDeadlineOf(id);
        vm.warp(workDeadline);
        vm.prank(stranger);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev the work deadline after: executor may stall
    function test_workdeadline_after_by_executor() public {
        uint256 id = _openWithDeadline();
        uint256 workDeadline = workDeadlineOf(id);
        vm.warp(workDeadline + 1);
        vm.prank(executor);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev the work deadline after: stranger may stall
    function test_workdeadline_after_by_stranger() public {
        uint256 id = _openWithDeadline();
        uint256 workDeadline = workDeadlineOf(id);
        vm.warp(workDeadline + 1);
        vm.prank(stranger);
        o.declareStalled(id);
        _assertState(id, Spectral.State.Stalled);
    }
    /// @dev the taker deadline before does not close a failed takeover
    function test_takerdeadline_before_closes() public {
        uint256 id = _takenWithDeadline();
        uint256 takerDeadline = takerDeadlineOf(id);
        vm.warp(takerDeadlineOf(id) - 1);
        vm.expectRevert(Spectral.DeadlineNotReached.selector);
        o.closeFailed(id);
        _assertState(id, Spectral.State.Taken);
    }
    /// @dev the taker deadline exactly_at closes a failed takeover
    function test_takerdeadline_exactly_at_closes() public {
        uint256 id = _takenWithDeadline();
        uint256 takerDeadline = takerDeadlineOf(id);
        vm.warp(takerDeadline);
        o.closeFailed(id);
        _assertState(id, Spectral.State.Closed);
    }
    /// @dev the taker deadline after closes a failed takeover
    function test_takerdeadline_after_closes() public {
        uint256 id = _takenWithDeadline();
        uint256 takerDeadline = takerDeadlineOf(id);
        vm.warp(takerDeadline + 1);
        o.closeFailed(id);
        _assertState(id, Spectral.State.Closed);
    }

    // ================= E. arithmetic =================

    /// @dev escrow for 1 units at price 0 is exact
    function test_escrow_1_units_at_price_0() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 0}(executor, 1, 0, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 1);
        assertEq(p, 0);
        assertEq(e, 0);
    }
    /// @dev escrow for 2 units at price 0 is exact
    function test_escrow_2_units_at_price_0() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 0}(executor, 2, 0, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 2);
        assertEq(p, 0);
        assertEq(e, 0);
    }
    /// @dev escrow for 3 units at price 0 is exact
    function test_escrow_3_units_at_price_0() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 0}(executor, 3, 0, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 3);
        assertEq(p, 0);
        assertEq(e, 0);
    }
    /// @dev escrow for 1 units at price 1 is exact
    function test_escrow_1_units_at_price_1() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 1 * 1}(executor, 1, 1, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 1);
        assertEq(p, 1);
        assertEq(e, 1 * 1);
    }
    /// @dev escrow for 2 units at price 1 is exact
    function test_escrow_2_units_at_price_1() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 2 * 1}(executor, 2, 1, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 2);
        assertEq(p, 1);
        assertEq(e, 2 * 1);
    }
    /// @dev escrow for 3 units at price 1 is exact
    function test_escrow_3_units_at_price_1() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 3 * 1}(executor, 3, 1, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 3);
        assertEq(p, 1);
        assertEq(e, 3 * 1);
    }
    /// @dev escrow for 1 units at price 2 is exact
    function test_escrow_1_units_at_price_2() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 1 * 2}(executor, 1, 2, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 1);
        assertEq(p, 2);
        assertEq(e, 1 * 2);
    }
    /// @dev escrow for 2 units at price 2 is exact
    function test_escrow_2_units_at_price_2() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 2 * 2}(executor, 2, 2, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 2);
        assertEq(p, 2);
        assertEq(e, 2 * 2);
    }
    /// @dev escrow for 3 units at price 2 is exact
    function test_escrow_3_units_at_price_2() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 3 * 2}(executor, 3, 2, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 3);
        assertEq(p, 2);
        assertEq(e, 3 * 2);
    }
    /// @dev escrow for 1 units at price 1000000 is exact
    function test_escrow_1_units_at_price_1000000() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 1 * 1000000}(executor, 1, 1000000, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 1);
        assertEq(p, 1000000);
        assertEq(e, 1 * 1000000);
    }
    /// @dev escrow for 2 units at price 1000000 is exact
    function test_escrow_2_units_at_price_1000000() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 2 * 1000000}(executor, 2, 1000000, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 2);
        assertEq(p, 1000000);
        assertEq(e, 2 * 1000000);
    }
    /// @dev escrow for 3 units at price 1000000 is exact
    function test_escrow_3_units_at_price_1000000() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: 3 * 1000000}(executor, 3, 1000000, block.timestamp + DAY);
        (, , uint256 tu, uint256 p, uint256 e, , , , , , , ) = o.jobs(id2);
        assertEq(tu, 3);
        assertEq(p, 1000000);
        assertEq(e, 3 * 1000000);
    }
    /// @dev overflowing escrow (huge_units) panics rather than wrapping
    function test_escrow_overflow_huge_units() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert();
        o.createJob{value: 0}(executor, type(uint256).max, 2, block.timestamp + DAY);
    }
    /// @dev overflowing escrow (huge_price) panics rather than wrapping
    function test_escrow_overflow_huge_price() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert();
        o.createJob{value: 0}(executor, 2, type(uint256).max, block.timestamp + DAY);
    }
    /// @dev overflowing escrow (max_both) panics rather than wrapping
    function test_escrow_overflow_max_both() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert();
        o.createJob{value: 0}(executor, type(uint256).max, type(uint256).max, block.timestamp + DAY);
    }
    /// @dev one wei short of the exact escrow is refused
    function test_escrow_one_wei_short_refused() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BadEscrow.selector, ESCROW));
        o.createJob{value: ESCROW - 1}(executor, UNITS, PPU, block.timestamp + DAY);
    }
    /// @dev one wei over the exact escrow is refused
    function test_escrow_one_wei_over_refused() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert(abi.encodeWithSelector(Spectral.BadEscrow.selector, ESCROW));
        o.createJob{value: ESCROW + 1}(executor, UNITS, PPU, block.timestamp + DAY);
    }
    /// @dev a job with no units cannot exist
    function test_zero_units_refused() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert(Spectral.UnitOutOfRange.selector);
        o.createJob{value: 0}(executor, 0, PPU, block.timestamp + DAY);
    }
    /// @dev a job with no executor cannot exist
    function test_zero_executor_refused() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectRevert(Spectral.NotExecutor.selector);
        o.createJob{value: ESCROW}(address(0), UNITS, PPU, block.timestamp + DAY);
    }

    // ================= F. events =================

    /// @dev createJob announces the job
    function test_event_jobcreated() public {
        uint256 id = _open();
        vm.prank(buyer);
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.JobCreated(2, buyer, executor, 4, PPU, id);
        o.createJob{value: 4 * PPU}(executor, 4, PPU, id);
    }
    /// @dev counting a unit announces it
    function test_event_unitcounted() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.UnitCounted(id, 3, bytes32(uint256(7)), executor);
        o.countUnit(id, 3, bytes32(uint256(7)));
    }
    /// @dev the stall is announced
    function test_event_stalled() public {
        uint256 id = _open();
        vm.prank(executor);
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.Stalled(id, executor);
        o.declareStalled(id);
    }
    /// @dev the listing is announced
    function test_event_listed() public {
        uint256 id = _stalled();
        uint256 dl = block.timestamp + DAY;
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.Listed(id, dl);
        o.listObligation(id, dl);
    }
    /// @dev the takeover is announced
    function test_event_taken() public {
        uint256 id = _listed();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.Taken(id, taker, required);
        o.takeObligation{value: required}(id);
    }
    /// @dev completion announces settlement with the exact payout
    function test_event_settled() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < UNITS - 1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.Settled(id, ESCROW, 0);
        o.countUnit(id, UNITS - 1, bytes32(uint256(99)));
        vm.stopPrank();
    }
    /// @dev the failure announces the refund and the forfeited bond
    function test_event_closed() public {
        uint256 id = _takenPartial();
        uint256 bond = o.requiredBond(id);
        uint256 remainder = (UNITS - 2) * PPU;
        vm.warp(block.timestamp + DAY + 1);
        vm.expectEmit(true, true, true, true, address(o));
        emit Spectral.Closed(id, remainder + bond, bond);
        o.closeFailed(id);
    }

    // ================= G. isolation =================

    /// @dev counting in one job cannot move another
    function test_isolation_two_jobs_are_separate() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: ESCROW}(stranger, UNITS, PPU, block.timestamp + DAY);
        assertEq(o.remainingUnits(id), UNITS);
        assertEq(o.remainingUnits(id2), UNITS);
        vm.prank(executor);
        o.countUnit(id, 0, bytes32(uint256(1)));
        assertEq(o.remainingUnits(id), UNITS - 1);
        assertEq(o.remainingUnits(id2), UNITS);
    }
    /// @dev settling one job leaves the other's escrow locked and still in the venue
    function test_isolation_settling_one_leaves_the_other_live() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: ESCROW}(stranger, UNITS, PPU, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        _assertState(id2, Spectral.State.Open);
        assertEq(o.credits(executor), ESCROW);
        assertEq(address(o).balance, 2 * ESCROW);
    }
    /// @dev closing one job cannot close another
    function test_isolation_closing_one_leaves_the_other_live() public {
        uint256 id = _takenPartial();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: ESCROW}(stranger, UNITS, PPU, block.timestamp + DAY);
        vm.warp(block.timestamp + DAY + 1);
        o.closeFailed(id);
        _assertState(id2, Spectral.State.Open);
    }
    /// @dev each account's credit is its own and is paid exactly once
    function test_isolation_claim_is_per_account() public {
        uint256 id = _closed();
        address[3] memory who = [buyer, executor, taker];
        for (uint256 k; k < 3; k++) {
            uint256 owed = o.credits(who[k]);
            if (owed == 0) {
                vm.prank(who[k]);
                vm.expectRevert(Spectral.NothingToClaim.selector);
                o.claim();
            } else {
                uint256 before = who[k].balance;
                vm.prank(who[k]);
                o.claim();
                assertEq(who[k].balance - before, owed);
                assertEq(o.credits(who[k]), 0);
            }
        }
    }
    /// @dev one party claiming leaves the other's credit reserved
    function test_isolation_partial_claim_leaves_others_intact() public {
        uint256 id = _closed();
        uint256 buyerOwed = o.credits(buyer);
        uint256 execOwed = o.credits(executor);
        vm.prank(executor);
        o.claim();
        assertEq(o.credits(executor), 0);
        assertEq(o.credits(buyer), buyerOwed);
        assertEq(address(o).balance, buyerOwed);
        assertGt(execOwed, 0);
    }
    /// @dev a credit cannot be claimed twice
    function test_isolation_second_claim_refused() public {
        uint256 id = _closed();
        vm.startPrank(buyer);
        o.claim();
        vm.expectRevert(Spectral.NothingToClaim.selector);
        o.claim();
        vm.stopPrank();
    }
    /// @dev job ids are sequential and never reused
    function test_isolation_jobcount_monotonic() public {
        uint256 id = _open();
        vm.prank(buyer);
        uint256 id2 = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
        vm.prank(buyer);
        uint256 id3 = o.createJob{value: ESCROW}(executor, UNITS, PPU, block.timestamp + DAY);
        assertEq(id2, 2);
        assertEq(id3, 3);
        assertEq(o.jobCount(), 3);
        assertEq(id, 1);
    }
    /// @dev only the first taker can take the obligation
    function test_isolation_two_takers_one_slot() public {
        uint256 id = _listed();
        uint256 required = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: required}(id);
        vm.prank(stranger);
        vm.expectRevert(Spectral.NothingToTake.selector);
        o.takeObligation{value: required}(id);
    }

    // ================= H. sequences =================

    /// @dev 1 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_1_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 1);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 2 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_2_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 2; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 2);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 3 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_3_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 3; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 3);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 4 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_4_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 4; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 4);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 5 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_5_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 5; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 5);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 6 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_6_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 6; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 6);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 7 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_7_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 7; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 7);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 8 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_8_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 8; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 8);
        assertEq(o.credits(executor), 0);
    }
    /// @dev 9 of 10 units counted leaves the job open with no payout
    function test_sequence_open_after_9_units() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 9; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.remainingUnits(id), 10 - 9);
        assertEq(o.credits(executor), 0);
    }
    /// @dev the last unit settles, and only the last unit settles
    function test_sequence_settles_on_unit_10() public {
        uint256 id = _open();
        vm.startPrank(executor);
        for (uint256 i; i < 10 - 1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        _assertState(id, Spectral.State.Open);
        o.countUnit(id, 10 - 1, bytes32(uint256(42)));
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), ESCROW);
        assertEq(o.remainingUnits(id), 0);
        vm.stopPrank();
    }
    /// @dev the whole continuation path, with each party paid for what it counted
    function test_sequence_stall_then_list_then_take_then_finish() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 0, bytes32(uint256(1)));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
        _assertState(id, Spectral.State.Listed);
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        _assertState(id, Spectral.State.Taken);
        vm.startPrank(taker);
        for (uint256 i = 1; i < UNITS; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Settled);
        assertEq(o.credits(executor), PPU);
        assertEq(o.credits(taker), (UNITS - 1) * PPU + bond);
    }
    /// @dev a taker who counts nothing forfeits the bond to the buyer
    function test_sequence_take_then_fail_then_close() public {
        uint256 id = _open();
        vm.startPrank(executor);
        o.countUnit(id, 0, bytes32(uint256(1)));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
        uint256 bond = o.requiredBond(id);
        vm.prank(taker);
        o.takeObligation{value: bond}(id);
        vm.warp(block.timestamp + DAY + 1);
        o.closeFailed(id);
        _assertState(id, Spectral.State.Closed);
        assertEq(o.credits(executor), PPU);
        assertEq(o.credits(buyer), (UNITS - 1) * PPU + bond);
        assertEq(o.credits(taker), 0);
    }

    // ================= I. fuzz =================

    /// @dev conservation over arbitrary workloads: sum of credits plus in-flight equals balance
    function testFuzz_matrix_conservation(uint96 escrowUnits, uint256 ppu, uint256 execUnits, uint256 takerUnits) public {
        uint256 units = bound(uint96(escrowUnits), 1, 4);
        ppu = bound(ppu, 0, 1 ether);
        uint256 esc = units * ppu;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, units, ppu, block.timestamp + DAY);

        uint256 e = bound(execUnits, 0, units);
        uint256 t = bound(takerUnits, 0, units - e);
        vm.startPrank(executor);
        for (uint256 i; i < e; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        if (e < units) o.declareStalled(id);
        vm.stopPrank();
        if (e < units) {
            o.listObligation(id, block.timestamp + DAY);
            uint256 bond = o.requiredBond(id);
            vm.prank(taker);
            o.takeObligation{value: bond}(id);
            vm.startPrank(taker);
            for (uint256 i = e; i < e + t; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
            vm.stopPrank();
        }
        uint256 owed = o.credits(buyer) + o.credits(executor) + o.credits(taker);
        uint256 inFlight;
        if (o.stateOf(id) != Spectral.State.Settled) {
            inFlight = esc;
            if (o.stateOf(id) == Spectral.State.Taken) {
                (, , , , , , , , , , uint256 bondHeld, ) = o.jobs(id);
                inFlight += bondHeld;
            }
        }
        assertEq(address(o).balance, owed + inFlight, "conservation broken");
    }

    /// @dev the executor's credit is always exactly what it counted, at any price
    function testFuzz_matrix_executor_paid_for_counted_units(uint128 ppu, uint8 counted) public {
        uint256 price = bound(uint128(ppu), 0, 1 ether);
        uint256 n = bound(uint8(counted), 1, 6);
        uint256 esc = n * price;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, n, price, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < n; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertEq(o.credits(executor), n * price);
        assertEq(address(o).balance, n * price);
    }

    /// @dev the required bond is always exactly half the remaining escrow
    function testFuzz_matrix_bond_is_half_the_remainder(uint8 total, uint8 counted) public {
        uint256 units = bound(uint8(total), 2, 8);
        uint256 c = bound(uint8(counted), 0, units - 1);
        uint256 price = 1 ether;
        uint256 esc = units * price;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, units, price, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < c; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        o.declareStalled(id);
        vm.stopPrank();
        o.listObligation(id, block.timestamp + DAY);
        uint256 remaining = units - c;
        assertEq(o.remainingUnits(id), remaining);
        assertEq(o.requiredBond(id), (remaining * price) / 2);
    }

    /// @dev a job can never settle with units outstanding
    function testFuzz_matrix_no_settlement_with_units_outstanding(uint8 counted) public {
        uint256 n = 5;
        uint256 c = bound(uint8(counted), 0, n - 1);
        vm.prank(buyer);
        uint256 id = o.createJob{value: n * PPU}(executor, n, PPU, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < c; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        _assertState(id, Spectral.State.Open);
        assertEq(o.credits(executor), 0);
        assertEq(address(o).balance, n * PPU);
    }

    /// @dev no sequence of counts can make a party's credit exceed the escrow it is paid from
    function testFuzz_matrix_credits_never_exceed_escrow(uint8 n, uint8 c) public {
        uint256 units = bound(uint8(n), 1, 6);
        uint256 c1 = bound(uint8(c), 0, units);
        uint256 esc = units * PPU;
        vm.deal(buyer, esc);
        vm.prank(buyer);
        uint256 id = o.createJob{value: esc}(executor, units, PPU, block.timestamp + DAY);
        vm.startPrank(executor);
        for (uint256 i; i < c1; i++) o.countUnit(id, i, bytes32(uint256(i) + 1));
        vm.stopPrank();
        assertLe(o.credits(executor), esc);
        assertLe(o.credits(buyer) + o.credits(executor) + o.credits(taker), esc);
    }
}
